### ISSUE TITLE
EC signature failed

### ISSUE THREAD

**Issue by SunilAruruios** [cbaker6/CertificateSigningRequestSwift_Test#1]
I'm trying to build EC 256 CSR but every time it's showing signing failed. Can any one time tell me what's the wrong here?
-----BEGIN CERTIFICATE REQUEST----- MIIBFTCBuwIBADBZMQswCQYDVQQGDAJVUzENMAsGA1UECgwEVGVzdDENMAsGA1UE CwwEVGVzdDEsMCoGA1UEAwwjQ2VydGlmaWNhdGVTaWduaW5nUmVxdWVzdFN3aWZ0 IFRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATC24iJCr7abrZN0BPaYcM+ cKd/4iXBtHuIM4LzOszsU5pQ9dc9s+srChfWu6m1nCgN48ZHwApTyKV/O0yWWcLA oAAwCgYIKoZIzj0EAwIDSQAwRgIhAPI2FW/izEz8SHAMStctamIzTne+g6AHQWai X0OfkwoBAiEAzXqgv6WVn+VMyxiA25eMc8/Zzrj/mWpew6INRZ1pA1g= -----END CERTIFICATE REQUEST-----

**Comment by sirowain** [comment]
I also get a Signature error with building rsa 256 CSR. Any suggestions?

**Comment by sirowain** [comment]
Oddly also the CSR in the README.md has invalid Signature according to https://redkestrel.co.uk/products/decoder/

**Comment by cbaker6** [comment]
@SunilAruruios and @sirowain Can you try this again? Everything checks out fine when I run:

-----BEGIN CERTIFICATE REQUEST-----
MIIBMDCB1wIBADB1MQswCQYDVQQGDAJVUzELMAkGA1UECAwCS1kxDTALBgNVBAcM
BFRlc3QxDTALBgNVBAoMBFRlc3QxDTALBgNVBAsMBFRlc3QxLDAqBgNVBAMMI0Nl
cnRpZmljYXRlU2lnbmluZ1JlcXVlc3RTd2lmdCBUZXN0MFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEFmNP4DqVYkWZmLQiwu32vKoWu5dF9B8W3ENSgLWfZJPoPKjB
8lSZV9cR8R01//5BT62V4nEV9Luebo/xFKdxDKAAMAoGCCqGSM49BAMCA0gAMEUC
IGxOTJdJut/E63DGPCljGgHPsPfEggXEDwt7JzwAYQShAiEAxCKswuPFsbaDWh71
e3jK1WuL0y66EQnhHCyWgxLvNPY=
-----END CERTIFICATE REQUEST-----
