### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by sanderdekoning** [cbaker6/CertificateSigningRequestSwift_Test#2]
All my CSRs created with this library have an invalid signature. The CSR example that is given in the readme(copied below) also has an invalid signature. How can I resolve this problem?

`-----BEGIN CERTIFICATE REQUEST----- MIIBFTCBuwIBADBZMQswCQYDVQQGDAJVUzENMAsGA1UECgwEVGVzdDENMAsGA1UE CwwEVGVzdDEsMCoGA1UEAwwjQ2VydGlmaWNhdGVTaWduaW5nUmVxdWVzdFN3aWZ0 IFRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATC24iJCr7abrZN0BPaYcM+ cKd/4iXBtHuIM4LzOszsU5pQ9dc9s+srChfWu6m1nCgN48ZHwApTyKV/O0yWWcLA oAAwCgYIKoZIzj0EAwIDSQAwRgIhAPI2FW/izEz8SHAMStctamIzTne+g6AHQWai X0OfkwoBAiEAzXqgv6WVn+VMyxiA25eMc8/Zzrj/mWpew6INRZ1pA1g= -----END CERTIFICATE REQUEST-----`

**Comment by cbaker6** [comment]
This is a keychain issue, not an issue with this framework. You need to either remove the keys with the same tag from your keychain or to reuse the key with the same tag. See here: https://github.com/cbaker6/CertificateSigningRequest/issues/14#issuecomment-620304226
